version: '3.8'

services:
  # MySQL database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "3307:3306"  # Use 3307 on host, but 3306 inside container
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network  # Added network

  # Spring Boot application (backend)
  app:
    build:
      context: Task-Management-System  # Ensure this is the correct backend project folder
    container_name: task_management_app_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/task_db  # Correct database host
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network  # Added network

  # React frontend
  frontend:
    build:
      context: task-management-system-front-end  # Ensure this is the correct frontend project folder
    container_name: task_management_app_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network  # Ensure frontend can communicate with the backend

# Define a network for internal communication
networks:
  app-network:
    driver: bridge

# Define persistent volume for MySQL
volumes:
  mysql_data:
