spring:
  application:
    name: Task-Management-System

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Hasitha@8465

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
